site_name: First Foundation
nav:
  - Home: index.md
  - User Guide: 
    - User Guides: usrg_userguides.md
    - Windows Sample: usrg_win_sample.md
  - Education: 
    - Cyber Security: edu_cyber_sec.md
    - Programming: edu_programming.md

theme: readthedocs